export const DEMO_TOKEN_ABI = [
  "function balanceOf(address) view returns (uint256)",
  "function allowance(address owner, address spender) view returns (uint256)",
  "function approve(address spender, uint256 value) returns (bool)",
  "function faucet()",
  "function FAUCET_AMOUNT() view returns (uint256)",
  "function FAUCET_COOLDOWN() view returns (uint256)",
  "function lastFaucetClaim(address) view returns (uint256)",
];

export const FLIGHT_DELAY_INSURANCE_ABI = [
  "function PREMIUM() view returns (uint256)",
  "function PAYOUT() view returns (uint256)",
  "function WARNING_LINE() view returns (uint256)",
  "function SALE_CUTOFF() view returns (uint256)",
  "function DELAY_THRESHOLD_MIN() view returns (uint256)",
  "function REPORT_TIMEOUT() view returns (uint256)",
  "function insurer() view returns (address)",
  "function oracle() view returns (address)",
  "function paused() view returns (bool)",
  "function reservedPayouts() view returns (uint256)",
  "function poolBalance() view returns (uint256)",
  "function flightCount() view returns (uint256)",
  "function policyCount() view returns (uint256)",
  "function flights(uint256) view returns (string flightNo, string origin, uint256 scheduledArrival, bool sellable, bool exists)",
  "function policies(uint256) view returns (address holder, uint256 flightId, uint256 requestId, uint8 status)",
  "function flightResults(uint256) view returns (bool isFinal, bool cancelled, uint256 actualArrival, uint256 delayMinutes, string dataDate, bytes32 evidenceHash)",
  "function hasPolicyForFlight(uint256, address) view returns (bool)",
  "function fundPool(uint256 amount)",
  "function withdrawSurplus(uint256 amount)",
  "function registerFlight(string flightNo, string origin, uint256 scheduledArrival, bool sellable) returns (uint256)",
  "function setFlightSellable(uint256 flightId, bool sellable)",
  "function setOracle(address newOracle)",
  "function pause()",
  "function unpause()",
  "function buyPolicy(uint256 flightId) returns (uint256)",
  "function requestVerification(uint256 policyId)",
  "function settlePolicy(uint256 policyId)",
  "function refundUnresolved(uint256 policyId)",
  "event PolicyBought(uint256 indexed policyId, address indexed holder, uint256 indexed flightId)",
  "event FlightRegistered(uint256 indexed flightId, string flightNo, string origin, uint256 scheduledArrival, bool sellable)",
  "event PolicySettled(uint256 indexed policyId, address indexed holder, uint256 amountPaid, string reason)",
  "event PolicyRefunded(uint256 indexed policyId, address indexed holder, uint256 amount)",
];

export const POLICY_STATUS_LABELS = ["Active", "Verifying", "Paid out", "Closed (no payout)", "Refunded"] as const;
